<div id="form">
<?php

// Supprimer les decorateurs existants pour les redéfinir
$this->createForm->clearDecorators();

// Redéfinition des décorateurs nécessaires

$this->createForm->firstname->setLabel('Prenom')
		                            ->setAttrib('class' , 'formField')
		                            ->setDescription('Entrez votre prenom')
		                            ->setDecorators(array(
		                                      'ViewHelper',
		                                      array( 'Label', array( 'class' => 'formLabel')),
		                                      // array('Description', array('class' => 'test')),
		                                      'Errors',
		                                      array( 'HtmlTag', array('tag' => 'p'))
		                                   	 )
                             );

$this->createForm->lastname->setLabel('Nom')
                                    ->setAttrib('class' , 'formField')
                                    ->setDescription('Entrez votre nom')
                                    ->setDecorators(array(
                                            'ViewHelper',
                                            array( 'Label', array( 'class' => 'formLabel')),
                                           // array('Description', array('class' => 'test')),
                                            'Errors',
                                            array( 'HtmlTag', array('tag' => 'p'))
                                        )
                                    );
                                    
$this->createForm->submit->setLabel('Connexion')
                                       ->setAttrib('class' , 'formBtn')
                                        ->setDecorators(array(
                                            'ViewHelper',
                                            array( 'HtmlTag', array('tag' => 'p'))
                                        )
                                    );

echo $this->createForm->setDecorators(
    array(
        'FormElements',
        'Form'
    )
);
?>

</div>