<?php

// Supprimer les decorateurs existants pour les redéfinir
$this->editForm->clearDecorators();

// Redéfinition des décorateurs nécessaires
$this->editForm->firstname->setLabel('Prenom')
                            ->setAttrib('class' , 'formField')
                            ->setDescription('Entrez votre prénom')
                            ->setDecorators(array(
                                      'ViewHelper',
                                      array( 'Label', array( 'class' => 'formLabel')),
                                      // array('Description', array('class' => 'test')),
                                      'Errors',
                                      array( 'HtmlTag', array('tag' => 'p'))
                                   	  )
                             );

$this->editForm->email->setLabel('Courriel')
                         ->setAttrib('class' , 'formField')
                         ->setDescription('Entrez votre nom')
                         ->setDecorators(array(
                                  'ViewHelper',
                                  array( 'Label', array( 'class' => 'formLabel')),
                                  // array('Description', array('class' => 'test')),
                                  'Errors',
                                  array( 'HtmlTag', array('tag' => 'p'))
                                  )
                         );
                         
$this->editForm->lastname->setLabel('Nom')
                         ->setAttrib('class' , 'formField')
                         ->setDescription('Entrez votre nom')
                         ->setDecorators(array(
                                  'ViewHelper',
                                  array( 'Label', array( 'class' => 'formLabel')),
                                  // array('Description', array('class' => 'test')),
                                  'Errors',
                                  array( 'HtmlTag', array('tag' => 'p'))
                                  )
                         );

$this->editForm->login->setLabel('Nom d\'utilisateur')
                         ->setAttrib('class' , 'formField')
                         ->setDescription('Entrez votre nom')
                         ->setDecorators(array(
                                  'ViewHelper',
                                  array( 'Label', array( 'class' => 'formLabel')),
                                  // array('Description', array('class' => 'test')),
                                  'Errors',
                                  array( 'HtmlTag', array('tag' => 'p'))
                                  )
                         );

$this->editForm->password->setLabel('Mot de passe')
                         ->setAttrib('class' , 'formField')
                         ->setDescription('Entrez votre nom')
                         ->setDecorators(array(
                                  'ViewHelper',
                                  array( 'Label', array( 'class' => 'formLabel')),
                                  // array('Description', array('class' => 'test')),
                                  'Errors',
                                  array( 'HtmlTag', array('tag' => 'p'))
                                  )
                         );
                         
$this->editForm->submit->setLabel('Modifier')
                                       ->setAttrib('class' , 'formBtn')
                                        ->setDecorators(array(
                                            'ViewHelper',
                                            array( 'HtmlTag', array('tag' => 'p'))
                                        )
                                    );

echo $this->editForm->setDecorators(
    array(
        'FormElements',
        'Form'
    )
);
