<table>
<tr>
	<th>Utilisateur</th>
	<th>Prenom</th>
	<th>Nom</th>
	<th>eMail</th>
	<th>Equipe</th>
	<th>Modifier</th>
	<th>Supprimer</th>
</tr>
<?php  foreach ($this->staffmembres as $staffmembre) : ?>
  <tr>
      <td><?php echo $staffmembre->getLogin() ?></td>
      <td><?php echo $staffmembre->getFirstname() ?></td>
      <td><?php echo $staffmembre->getLastname() ?></td>
      <td><?php echo $staffmembre->getEmail() ?></td>
      <td><?php echo $staffmembre->getTeam() ?></td>
      <td><a href="<?php echo $this->url(array('id' => $staffmembre->getId() ), 'UserEdit') ?>" title="Modifier l'Utilisateur"><img src="../img/modif.png"/></a></td>
      <td><a href="<?php echo $this->url(array('id' => $staffmembre->getId() ), 'UserDelete') ?>" title="Supprimer l'Utilisateur"><img src="../img/error.png"/></a></td>
  </tr>
<?php endforeach;?>
</table>

<p><a href="/user/staffmembre/insert" title="create"><img src="../img/add.png" title="ajouter un Utilisateur" /></a></p>