<?php

// Supprimer les decorateurs existants pour les redéfinir
$this->saveForm->clearDecorators();

// Redéfinition des décorateurs nécessaires

$this->saveForm->firstname->setLabel('Prénom')
                            ->setAttrib('class' , 'formField')
                            ->setDescription('Entrez votre prénom')
                            ->setDecorators(array(
                                      'ViewHelper',
                                      array( 'Label', array( 'class' => 'formLabel')),
                                      // array('Description', array('class' => 'test')),
                                      'Errors',
                                      array( 'HtmlTag', array('tag' => 'p'))
                                   	 )
                             );

$this->saveForm->lastname->setLabel('Nom')
                                    ->setAttrib('class' , 'formField')
                                    ->setDescription('Entrez votre nom')
                                    ->setDecorators(array(
                                            'ViewHelper',
                                            array( 'Label', array( 'class' => 'formLabel')),
                                           // array('Description', array('class' => 'test')),
                                            'Errors',
                                            array( 'HtmlTag', array('tag' => 'p'))
                                        )
                                    );
                                    
$this->saveForm->submit->setLabel('Connexion')
                                       ->setAttrib('class' , 'formBtn')
                                        ->setDecorators(array(
                                            'ViewHelper',
                                            array( 'HtmlTag', array('tag' => 'p'))
                                        )
                                    );

echo $this->saveForm->setDecorators(
    array(
        'FormElements',
        'Form'
    )
);