<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf8'); ?>
<?php echo $this->navigation()->links(Zend_Registry::get('navigation')).PHP_EOL; ?>
<?php $this->headLink()->appendStylesheet('/css/960.css','all'); ?>
<?php $this->headLink()->appendStylesheet('/css/template.css','all'); ?>
<?php $this->headLink()->appendStylesheet('/css/colour.css','all'); ?>
<?php $this->headLink()->appendStylesheet('/css/fonts.css','all'); ?>
<?php $this->headLink()->appendStylesheet('/css/demo_page.css','all'); ?>
<?php $this->headLink()->appendStylesheet('/css/demo_table.css','all'); ?>
<?php $this->headScript()->appendFile('/js/jquery-1.7.1.min.js', 'text/javascript');?>
<?php $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');?>
<?php echo $this->headLink();?>
<?php echo $this->headScript();?>
</head>
<body>

		<h1 id="head">Steal My Admin Template</h1>


		<?php echo $this->navigation()->menu(Zend_Registry::get('navigation'));?>

		
		<div id="content" class="container_16 clearfix">
		<div class="grid_13">
            <div class="breadcrumbs">
            	<a class="first" href="/index">My WebSite</a> &rarr;
            	<?php echo $this->navigation()
            	                    ->breadcrumbs(Zend_Registry::get('navigation'))
            	                    ->setSeparator(' &rarr; ')
            	                    ->setMinDepth(0)
            	                    ->setRenderInvisible(true); ?>
            </div>
        </div>
        <div class="grid_2">
            <?php 
            $userService = new User_Service_Staffmembre();
            if ( $userService->hasIdentity()) : ?>
                <a href="/User/auth/logout">D&eacute;connexion</a>
            <?php endif;?>
    	</div>
	<?php echo $this->layout()->content;?>
</div>

			<div id="foot">
				<i>Designed by </i><a href="http://mathew-davies.co.uk/">Mathew Davies</a>
			</div>
		
	</body>
</html>